version: '3.4'

# Network
networks:
  docker-network:
    driver: bridge
    ipam:
      config:
        - subnet: 182.34.0.0/24

## Volume
volumes:
  wordpress-data:
    name: wordpress-volume
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/$USER/data/wordpress

  mariadb-data:
    name: mariadb-volume
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/$USER/data/mariadb

## Services
services:

## MariaDB
  mariadb:
    image: mariadb:not-latest
    container_name: mariadb
    build: ./requirements/mariadb
    env_file:
      - .env
    volumes:
      - mariadb-data:/var/lib/mysql
    networks:
      - docker-network
    restart: always

## Wordpress
  wordpress:
    image: wordpress:not-latest
    container_name: wordpress
    build: ./requirements/wordpress
    env_file:
      - .env
    volumes:
      - wordpress-data:/var/www/html
    networks:
      - docker-network
    depends_on:
      - mariadb
    restart: always

## Nginx 
  nginx:
    image: nginx:not-latest
    container_name: nginx
    build: ./requirements/nginx
    volumes:
      - wordpress-data:/var/www/html
    networks:
      - docker-network
    ports:
      - 443:443
    depends_on:
      - mariadb
      - wordpress
    restart: always


## */-[ BONUS ]-\*

## Adminer
  adminer:
    image: adminer:not-latest
    container_name: adminer
    build: ./requirements/bonus/adminer
    networks:
      - docker-network
    ports:
      - 8080:8080
    depends_on:
      - mariadb
    restart: always

## Website
  website:
    image: website:not-latest
    container_name: website
    build: ./requirements/bonus/website
    networks:
      - docker-network
    ports:
      - 3000:3000
    restart: always

## Redis
  redis:
    image: redis:not-latest
    container_name: redis
    build: ./requirements/bonus/redis
    networks:
      - docker-network
    volumes:
      - wordpress-data:/var/www/html
    ports:
      - 6379:6379
    depends_on:
      - wordpress
    restart: always

## FTP-Server
  ftp-server:
    image: ftp-server:not-latest
    container_name: ftp-server
    build: ./requirements/bonus/ftp-server
    networks:
      - docker-network
    volumes:
      - wordpress-data:/var/www/html
    depends_on:
      - wordpress
    ports:
      - "20:20"
      - "21:21"
      - "22:22"
      - "64000-64321:64000-64321"
    env_file:
      - .env
    restart: always

## Windows
  windows:
    image: windows:not-latest
    container_name: windows
    build: ./requirements/bonus/windows
    depends_on:
      - qemu
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    environment:
      - VERSION=winxp
    stop_grace_period: 2m
    restart: on-failure

## Qemu
  qemu:
    image: qemu:not-latest
    container_name: qemu
    build: ./requirements/bonus/qemu
    restart: always