version: '3.4'

networks:
  docker-network:
    driver: bridge
    ipam:
      config:
        - subnet: 182.34.0.0/24

volumes:
  wordpress-data:
    name: wordpress-volume
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/$USER/data/wordpress

  mariadb-data:
    name: mariadb-volume
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/$USER/data/mariadb

services:

# MariaDB
  mariadb:
    image: mariadb:not-latest
    container_name: mariadb
    build: ./requirements/mariadb
    env_file:
      - .env
    volumes:
      - mariadb-data:/var/lib/mysql
    networks:
      - docker-network
    restart: always

# Wordpress
  wordpress:
    image: wordpress:not-latest
    container_name: wordpress
    build: ./requirements/wordpress
    env_file:
      - .env
    volumes:
      - wordpress-data:/var/www/html
    networks:
      - docker-network
    depends_on:
      - mariadb
    restart: always

# Nginx 
  nginx:
    image: nginx:not-latest
    container_name: nginx
    build: ./requirements/nginx
    volumes:
      - wordpress-data:/var/www/html
    networks:
      - docker-network
    ports:
      - 443:443
    depends_on:
      - mariadb
      - wordpress
    restart: always


# BONUS

# Adminer
  adminer:
    image: adminer:not-latest
    container_name: adminer
    build: ./requirements/bonus/adminer
    networks:
      - docker-network
    ports:
      - 8080:8080
    depends_on:
      - mariadb
    restart: always