version: "3.5"

networks:
  nw:
    name: my_network42
    driver: bridge

volumes:
  wp:
  db:

services:
 
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    env_file:
      - ./.env
    networks:
      - nw
    restart: unless-stopped
    volumes:
      - db:/var/lib/mysql
      
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    env_file:
      - ./.env
    networks:
      - nw
    depends_on:
      - mariadb
    restart: unless-stopped
    volumes:
      - wp:/var/www/html

  nginx:
    container_name: nginx
    build: ./requirements/nginx
    env_file:
      - ./.env
    ports:
      - "443:443"
    depends_on:
      - mariadb
      - wordpress
    volumes:
      - wp:/var/www/html
    networks:
      - nw
    restart: unless-stopped

